const express = require("express");
const router = express.Router();
const authRouter = require('../routes/auth');
const eventsRouter = require('../routes/events');
const itemsRouter = require('../routes/items');
const maintenanceRouter = require('../routes/maintenance');
const bookingsRouter = require('../routes/bookings'); 
const bulletinRouter = require('../routes/bulletin');
const pinsRouter = require('../routes/pins');
const notificationsRouter = require('../routes/notifications');
const usersRouter = require('../routes/users');
const directoryRouter = require('../routes/directory');
const lostFoundRouter = require('../routes/lostfound');
const servicesRouter = require('../routes/services');
const pollsRouter = require('../routes/polls');
const statsRouter = require('../routes/stats');
const channelsRouter = require('../routes/channels');
const wikiRouter = require('../routes/wiki');
const emergencyContactsRouter = require('../routes/emergency_contacts');
const clubsRouter = require('../routes/clubs');
const studyGroupsRouter = require('../routes/studygroups');
const documentsRouter = require('../routes/documents');
const suggestionsRouter = require("../routes/suggestions");
const galleryRouter = require('../routes/gallery');
const tutoringRouter = require('../routes/tutoring');
const jobPostsRouter = require('../routes/job_posts');
const securityReportsRouter = require('../routes/security_reports');

router.get("/", (req, res) => {
  res.json({ message: "API is running" });
}); 

router.use('/auth', authRouter);
router.use('/events', eventsRouter);
router.use('/items', itemsRouter);
router.use('/maintenance', maintenanceRouter);
router.use('/bookings', bookingsRouter); 
router.use('/bulletin', bulletinRouter);
router.use('/pins', pinsRouter);
router.use('/notifications', notificationsRouter);
router.use('/users', usersRouter);
router.use('/directory', directoryRouter);
router.use('/lostfound', lostFoundRouter);
router.use('/services', servicesRouter);
router.use('/polls', pollsRouter);
router.use('/stats', statsRouter);
router.use('/channels', channelsRouter);
router.use('/wiki', wikiRouter);
router.use('/emergency_contacts', emergencyContactsRouter);
router.use('/clubs', clubsRouter);
router.use('/studygroups', studyGroupsRouter);
router.use('/documents', documentsRouter);
router.use("/suggestions", suggestionsRouter);
router.use('/gallery', galleryRouter);
router.use('/tutoring', tutoringRouter);
router.use('/job_posts', jobPostsRouter);
router.use('/security_reports', securityReportsRouter);
module.exports = router;
