name: Flutter CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # ─────────── Set up & cache Flutter SDK ───────────
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'
          architecture: x64

      # ─────────── Cache Flutter (pub) dependencies ───────────
      - name: Cache Flutter pub‐cache
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-flutter-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-pub-

      - name: Install Flutter dependencies
        run: flutter pub get

      # ─────────── Run Flutter tests ───────────
      - name: Run Flutter tests
        run: flutter test
 
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # ─────────── Cache npm dependencies ───────────
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          # Make sure this path matches where your package.json lives:
          key: ${{ runner.os }}-node-${{ hashFiles('server/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install npm dependencies
        working-directory: server
        run: npm install

      - name: Run npm tests
        working-directory: server
        run: npm test
